
trigger:
  - main
variables:
    tag: '$(Build.BuildId)'
    repositoryName: 'soulredouane/jesa-php'
    phpVersion: '8.2.27'
    k8sNamespace: 'jesa-med-namespace'
    jobName: 'azp-agent-job'
    sonarHostUrl: 'http://sonarqube-sonarqube-lts.sonarqube.svc.cluster.local:9000'  # Fully qualified SonarQube service URL
    sonarToken: '95ed008304496205800ee04653a3189e62c3b9db'
stages: 
  - stage: Build_And_Test
    # dependsOn: Setup_Custom_Agent
    jobs:
      
      - job: BuildTest
        pool:
          name: 'default'
          demands:
            #  - agent.name -equals dockeragent-docker-agent
            - agent.name -equals dockeragent-soul-agent
        steps:
          - script: |
              sonar-scanner \
                -Dsonar.projectKey=azure-devops \
                -Dsonar.sources=. \
                -Dsonar.host.url=$(sonarHostUrl) \
                -Dsonar.login=$(sonarToken)
            displayName: 'Run SonarQube Scan'
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              repository: $(repositoryName)
              dockerfile: '**/Dockerfile'
              containerRegistry: dockerhub-registry
              tags: |
                $(tag)
          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              command: push
              repository: $(repositoryName)
              containerRegistry: dockerhub-registry
              tags: |
                $(tag)
                
