
trigger:
  - main
resources:
  repositories:
    - repository: k8s_agent_repo          # identifier to use in checkout
      type: github
      endpoint: 'github-repo'
      name: SOULREDOUANE/jesa-k8s-agent  # your repo name
      ref: main 
variables:
    tag: '$(Build.BuildId)'
    repositoryName: 'soulredouane/jesa-php'
    phpVersion: '8.2.27'
    k8sNamespace: 'jesa-med-ns'
    jobName: 'azp-agent-job'
    # sonarHostUrl: 'http://sonarqube-sonarqube-lts.sonarqube.svc.cluster.local:9000'  # Fully qualified SonarQube service URL
    # sonarToken: '088736885d6f6fa531ab2a2bbb2e8efc686e8626'
    # TRIVY_SERVICE_URL: 'http://trivy-service.trivy.svc.cluster.local:5000/scan'
stages: 
  - stage: Setup_Custom_Agent
    jobs:
    
    - job: CreateK8sAgent
      # pool:
      #   vmImage: 'ubuntu-latest'  # Start with Microsoft-hosted agent
      pool:
        name: 'default'
        demands:
          - agent.name -equals always-agent
      steps:
      - checkout: k8s_agent_repo
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Use the pipeline variable 'tag' to set REPORT_ID
            REPORT_ID="jesa-med-$(tag)"
            TAG="$(tag)"
            echo "Generated REPORT_ID: $REPORT_ID"
            kubectl create configmap report-config --from-literal=REPORT_ID="$REPORT_ID" --from-literal=TAG="$TAG" -n default
            kubectl apply -f $(System.DefaultWorkingDirectory)/k8s_manifests/owasp-job.yaml
            kubectl apply -f $(System.DefaultWorkingDirectory)/k8s_manifests/agent-job.yml
      # Wait for agent to be ready
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sleep 10
            # Wait for completion
            kubectl apply -f $(System.DefaultWorkingDirectory)/k8s_manifests/report-downloader.yaml -n default

            kubectl wait --for=condition=complete job/download-report-job -n default --timeout=5m || kubectl wait --for=condition=failed job/download-report-job -n default --timeout=5m
            
            # Copy the artifact from the pod to the agent
            POD_NAME=$(kubectl get pod -l job-name=dependency-check-job -n $(k8sNamespace) -o jsonpath="{.items[0].metadata.name}")
            #$(kubectl get pod -l job-name=download-report-job -n default -o jsonpath="{.items[0].metadata.name}")
            kubectl cp ${POD_NAME}:/output/dependency-check-report $(System.ArtifactsDirectory)/dependency-check-report -n default
                #Publish scan output as an artifact
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(System.ArtifactsDirectory)/dependency-check-report'
          artifactName: 'dependency-check-report'
          publishLocation: 'Container'
      - bash: |
          MAX_RETRIES=45
          RETRY_INTERVAL=10
          for ((i=1; i<=MAX_RETRIES; i++)); do
            RUNNING=$(kubectl get job $(jobName) -n $(k8sNamespace) -o jsonpath='{.status.active}')
            if [ "$RUNNING" == "1" ]; then
              echo "Agent is running!"
              exit 0
            fi
            echo "Waiting for agent to be ready... Attempt $i/$MAX_RETRIES"
            sleep $RETRY_INTERVAL
          done
          echo "Warning: Agent readiness check timed out, but continuing anyway..."
          exit 0  # Exit with success even if timeout
        displayName: 'Wait for K8s agent to be ready'

  - stage: Build_And_Test
    # dependsOn: Setup_Custom_Agent
    jobs:
      
      - job: BuildTest
        pool:
          name: 'default'
          demands:
            #  - agent.name -equals dockeragent-docker-agent
            - agent.name -equals jesa-med-job-agent
        steps:
          - script: |
              sonar-scanner \
                -Dsonar.projectKey=php-projec \
                -Dsonar.sources=. \
                -Dsonar.host.url=$(sonarHostUrl) \
                -Dsonar.login=$(sonarToken) \
                > sonar-scan-output.txt 2>&1
            displayName: 'Run SonarQube Scan'
          
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'sonar-scan-output.txt'
              artifactName: 'SonarQubeScanResults'
              publishLocation: 'Container'
            displayName: 'Publish SonarQube Scan Output'

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              repository: $(repositoryName)
              dockerfile: '**/Dockerfile'
              containerRegistry: dockerhub-registry
              tags: |
                $(tag)

          - script: |
              docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --exit-code 0 --no-progress --format json $(repositoryName):$(tag) > trivy-scan-result.json
            displayName: 'Scan Docker Image with Trivy CLI'

          # Publish Trivy scan results as an artifact
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'trivy-scan-result.json'
              artifactName: 'TrivyScanResult'
              publishLocation: 'Container'
            displayName: 'Publish Trivy Scan Result'

         
          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              command: push
              repository: $(repositoryName)
              containerRegistry: dockerhub-registry
              tags: |
                $(tag)
                
  - stage: Deploy
    # dependsOn: Build_And_Test
    # condition: succeeded()
    jobs:
      - job: DeployToDev
        pool:
          name: 'default'
          demands:
            - agent.name -equals  jesa-med-job-agent
        steps:
          - task: SSH@0
            displayName: 'Deploy to Dev Server'
            inputs:
              sshEndpoint: 'jesa-med-ssh'
              runOptions: 'commands'
              commands: |
                docker pull $(repositoryName):$(tag)
                docker rm -f jesa-php-container || true
                docker run -d --name jesa-php-container -p 8080:80 $(repositoryName):$(tag)
  - stage: CleanUP_Job_Agent
    jobs:
    - job: DeleteAgentJob
      # pool:
      #   vmImage: 'ubuntu-latest'  # Start with Microsoft-hosted agent
      pool:
        name: 'default'
        demands:
          - agent.name -equals always-agent
      steps:
      - checkout: k8s_agent_repo
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            kubectl delete -f $(System.DefaultWorkingDirectory)/k8s_manifests/agent-job.yml
            kubectl delete -f $(System.DefaultWorkingDirectory)/k8s_manifests/owasp-job.yaml
            kubectl delete cm report-config -n default 